//// <auto-generated />
//using System;
//using DATA.Context;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//namespace DATA.Migrations
//{
//    [DbContext(typeof(OsmoseInverseContext))]
//    [Migration("20240315104414_MG2")]
//    partial class MG2
//    {
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "3.1.32")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128)
//                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//            modelBuilder.Entity("Domain.Models.Atelier", b =>
//                {
//                    b.Property<Guid>("IdAtelier")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<Guid>("FK_Filiale")
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("Labelle")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("NomAtelier")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(30)")
//                        .HasMaxLength(30);

//                    b.HasKey("IdAtelier");

//                    b.HasIndex("FK_Filiale");

//                    b.ToTable("Atelier");
//                });

//            modelBuilder.Entity("Domain.Models.Filiale", b =>
//                {
//                    b.Property<Guid>("IdFiliale")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("Labelle")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("IdFiliale");

//                    b.ToTable("Filiale");
//                });

//            modelBuilder.Entity("Domain.Models.Station", b =>
//                {
//                    b.Property<Guid>("IdStation")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<int>("Capacite")
//                        .HasColumnType("int");

//                    b.Property<string>("Code")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<Guid>("FK_Atelier")
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("NomStation")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(30)")
//                        .HasMaxLength(30);

//                    b.Property<string>("TypeStation")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("IdStation");

//                    b.HasIndex("FK_Atelier");

//                    b.ToTable("Station");
//                });

//            modelBuilder.Entity("Domain.Models.Atelier", b =>
//                {
//                    b.HasOne("Domain.Models.Filiale", "Filiale")
//                        .WithMany("Ateliers")
//                        .HasForeignKey("FK_Filiale")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Domain.Models.Station", b =>
//                {
//                    b.HasOne("Domain.Models.Atelier", "Atelier")
//                        .WithMany("Stations")
//                        .HasForeignKey("FK_Atelier")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
